#
# Platform independent Docker compose configuration that syncs out a git branch
# (master is default) and/or a tag, and produced distribution installers for it.
# This is equivalent to ./gradlew installDist, where all platform archives,
# including Windows exe files, are built in the container.
#
# The build volume persists, and is rebuilt whenever it is detected that we
# want to build a branch at a change that doesn't correspond to the last build
# state. The cache volume also persiscat ~ts, so significant info is reused.
# 

version: '3.8'

#
# Set up secrets from the default locations, so that we can do things like
# publications, artifact signing or other Gradle operations, where sensitive
# information is stored outside the repository.
#
secrets:
  gradle_properties:
    file: ~/.gradle/gradle.properties

# gradle_cache is placed under /.root
# we also add a platform volume to reuse ~/xqiz.it
volumes:
  build:

services:
  platform:
    image: ghcr.io/xtclang/xdk-platform:latest
    build:
      context: docker
      dockerfile: Dockerfile.platform
      args:
        DOCKER_BUILDKIT: 1
        PLATFORM_PASSWORD: ${PLATFORM_PASSWORD:-password}
        GITHUB_BRANCH_PLATFORM: ${GITHUB_BRANCH_PLATFORM:-platform-xtcplugin}
        GITHUB_BRANCH_XVM: ${GITHUB_BRANCH_XVM:-master}
    secrets:
      - gradle_properties
    volumes:
      - build:/cache
    env_file:
      - docker/.env
      - docker/.env.local
    extra_hosts:
      - "xtc-platform.localhost.xqiz.it:127.0.0.1"
      - "xtc-platform.xqiz.it:127.0.0.10"
    ports:
        - "8080:80"
        #- "8090:90"
    entrypoint: ['entrypoint.sh']
